# Make file for a Hammer project

# Make sure this is set to the top level directory containing module_top.mk
TOP_DIR = $(realpath ../../ee477-hammer-cad)

# Build directory location
OBJ_DIR = build

# If you change the names of these files, update them here to reflect.
INPUT_CFGS =cfg/cfg.yml cfg/src.yml
TB_CFGS = cfg/tb.yml

# Main Hammer Targets
include $(TOP_DIR)/module_top.mk
